server:
  port: 8120
spring:
  profiles:
    active: dev
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #服务注册地址

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    keyid: 
    keysecret: 
    bucketname: online-class-upload
